name: Test Self Hosted Runner

on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Say Hello
        run: echo "Hello from the self-hosted runner!"

