
name: Self_Host

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Print message
        run: echo "Workflow from main.yml is running!"
